# Generated by Django 4.2.1 on 2023-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_transaction_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=3),
        ),
    ]
