# Generated by Django 4.0 on 2023-06-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_acc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
